# Bibliotecas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/Projeto Arima - series temporais /chuva_mensal_sp.csv",sep=';')

In [ ]:
df.head()

,Ano,Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,1985,"184,9","242,9",230,59,"126,2","14,6",4,"21,8","126,1","71,1","111,3","155,2"
1,1986,"199,6",221,"218,7","106,5","113,1","3,9","30,3",---,"34,5","60,7","242,5","389,9"
2,1987,"525,8",---,"161,3","98,1","293,8","183,9","11,8","30,9","80,2","84,8","72,7","152,1"
3,1988,"268,7","224,4","189,2","175,1","224,9","58,6","1,3","0,2","28,4","173,9","100,2","289,8"
4,1989,"312,9","344,3","288,2","66,3","21,7","52,5","150,1","32,9","52,1","80,1",88,"236,7"

In [ ]:
df.shape

(38, 13)

In [ ]:
df.dtypes

Ano          object
Janeiro      object
Fevereiro    object
Março        object
Abril        object
Maio         object
Junho        object
Julho        object
Agosto       object
Setembro     object
Outubro      object
Novembro     object
Dezembro     object
dtype: object

Substituição das vírgulas por pontos

In [ ]:
df = df.apply( lambda x: x.str.replace(',', '.'))

Transformação das variáveis categóricas(str) para númericas(float) e substituição dos traços (---) pela média

In [ ]:
df['Janeiro'] = pd.to_numeric(df["Janeiro"].str.replace('---', '305.79'))
df['Fevereiro'] = pd.to_numeric(df['Fevereiro'].str.replace('---', '249.3'))
df['Março'] = pd.to_numeric(df['Março'].str.replace('---', '227.97'))
df['Abril'] = pd.to_numeric(df['Abril'].str.replace('---', '93.64'))
df['Maio'] = pd.to_numeric(df['Maio'].str.replace('---', '86.67'))
df['Junho'] = pd.to_numeric(df['Junho'].str.replace('---', '59.66'))
df['Julho'] = pd.to_numeric(df['Julho'].str.replace('---', '54.6'))
df['Agosto'] = pd.to_numeric(df['Agosto'].str.replace('---', '27.85'))
df['Setembro'] = pd.to_numeric(df['Setembro'].str.replace('---', '83.8'))
df['Outubro'] = pd.to_numeric(df['Outubro'].str.replace('---', '139.89'))
df['Novembro'] = pd.to_numeric(df['Novembro'].str.replace('---', '145.04'))
df['Dezembro'] = pd.to_numeric(df['Dezembro'].str.replace('---', '236.04'))

In [ ]:
df.dtypes

Ano           object
Janeiro      float64
Fevereiro    float64
Março        float64
Abril        float64
Maio         float64
Junho        float64
Julho        float64
Agosto       float64
Setembro     float64
Outubro      float64
Novembro     float64
Dezembro     float64
dtype: object

In [ ]:
df.head(40)

,Ano,Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,1985,184.90,242.9,230.00,59.00,126.20,14.60,4.0,21.80,126.1,71.10,111.30,155.20
1,1986,199.60,221.0,218.70,106.50,113.10,3.90,30.3,27.85,34.5,60.70,242.50,389.90
2,1987,525.80,249.3,161.30,98.10,293.80,183.90,11.8,30.90,80.2,84.80,72.70,152.10
3,1988,268.70,224.4,189.20,175.10,224.90,58.60,1.3,0.20,28.4,173.90,100.20,289.80
4,1989,312.90,344.3,288.20,66.30,21.70,52.50,150.1,32.90,52.1,80.10,88.00,236.70
5,1990,284.10,196.9,310.10,85.80,77.90,50.60,121.2,76.30,97.2,206.80,116.30,149.80
6,1991,330.70,340.3,522.40,200.30,43.30,96.80,28.2,37.30,101.4,168.00,67.30,237.90
7,1992,129.20,258.5,227.97,87.20,93.50,11.60,40.9,24.70,150.6,219.60,145.04,211.70
8,1993,221.50,225.7,110.00,84.60,133.90,74.70,11.2,40.80,210.1,134.10,125.50,170.50
9,1994,196.90,184.4,231.60,111.40,54.90,30.50,39.2,2.40,1.8,147.60,86.60,276.30
10,1995,373.80,383.1,267.70,73.90,79.70,31.20,46.8,1.50,44.2,202.60,115.10,236.04
11,1996,334.30,376.5,284.50,42.30,21.70,45.10,12.2,41.20,179.4,179.80,87.40,243.90
12,1997,235.00,187.6,57.10,63.20,88.20,124.70,12.5,28.80,118.0,151.80,236.30,217.40
13,1998,231.60,430.1,211.20,56.90,133.80,16.60,16.6,45.50,99.5,203.10,41.50,198.40
14,1999,305.79,339.0,162.30,34.90,47.20,86.30,31.0,0.00,76.9,64.50,76.00,100.40
15,2000,387.70,304.0,190.40,50.00,9.70,9.80,74.0,27.85,120.3,105.50,322.00,281.00
16,2001,283.10,221.9,241.20,28.70,85.00,31.00,31.7,26.90,82.3,213.10,181.60,292.90
17,2002,300.60,173.6,354.80,95.30,137.60,2.30,23.0,41.50,84.0,143.90,201.40,263.70
18,2003,443.40,141.5,250.20,45.50,36.60,20.70,24.5,27.60,41.5,176.70,133.00,89.90
19,2004,188.80,316.9,127.20,160.50,77.40,75.60,105.6,2.20,13.8,120.60,215.50,181.00
20,2005,378.30,95.9,202.10,137.30,177.10,35.10,39.8,11.50,150.3,195.30,96.60,140.10
21,2006,230.90,223.5,407.90,65.40,23.70,34.80,78.6,9.20,86.2,71.90,175.00,353.30
22,2007,208.70,301.0,240.20,67.60,63.10,17.20,134.3,0.10,27.4,167.20,211.70,268.70
23,2008,388.00,136.4,332.80,123.60,80.90,55.70,0.0,52.50,49.9,144.30,125.40,152.90
24,2009,356.40,145.0,73.60,75.30,58.10,28.30,157.7,27.85,198.9,157.40,237.20,294.50
25,2010,549.10,175.4,258.90,116.40,52.80,20.20,78.4,1.20,100.4,73.80,129.20,234.70
26,2011,428.40,349.5,265.10,142.00,40.10,81.30,1.5,49.70,10.7,218.20,73.40,393.70
27,2012,401.50,226.0,165.90,149.10,82.40,59.66,105.5,3.70,31.9,93.90,154.00,623.20
28,2013,321.70,372.1,175.00,103.40,39.40,210.90,168.8,15.30,45.1,110.70,76.60,139.90
29,2014,189.70,236.1,222.90,110.20,71.00,11.50,51.9,20.50,82.1,23.80,209.30,258.00
30,2015,249.30,303.5,265.90,100.40,87.20,25.40,62.7,40.50,280.9,139.89,145.04,221.90
31,2016,242.80,225.2,288.10,92.20,141.40,207.30,0.0,82.20,29.1,116.90,181.20,129.20
32,2017,305.79,249.3,120.80,156.30,166.10,101.60,0.2,53.40,12.0,121.20,174.40,169.60
33,2018,238.20,84.5,227.97,66.40,25.80,15.00,20.5,27.85,72.9,203.40,134.10,258.00
34,2019,305.79,315.5,318.50,172.30,97.30,59.00,195.1,6.70,73.7,75.90,170.80,249.00
35,2020,408.10,249.3,95.50,5.60,13.70,163.80,54.6,62.10,22.9,213.90,162.10,236.04
36,2021,373.30,174.1,137.80,55.70,86.67,59.66,54.6,27.85,83.8,139.89,145.04,236.04
37,Média:,305.79,249.3,227.97,93.64,86.67,59.66,54.6,27.85,83.8,139.89,145.04,236.04

Exclusão das linhas 36 e 37, a 36 apresentava em sua maioria valores null que foram substituidos pela média e a linha 37 é uma linha de média geral do próprio dataset

In [ ]:
df_chuvas = df.drop([36,37])

In [ ]:
df_chuvas.to_csv('df_chuvas_treated', index= False)